//import React from "react";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const header = (
    <div>
      <h1>R&D Reflections </h1>
      <p>By: Geoff Lord</p>
    </div>
  );

  const footer = (
    <div>
      <p>Thanks for reading!</p>
    </div>
  );

  return(
      <html>
        <body>
          {header}
          {children}
          {footer}
        </body>
      </html>
    );
}






//import type { Metadata } from "next";
//import { Inter } from "next/font/google";
//import "./globals.css";

//const inter = Inter({ subsets: ["latin"] });

//export const metadata: Metadata = {
//  title: "Geoff's Blog",
//  description: "Generated by create next app",
//};

//export default function RootLayout({
//  children,
//}: Readonly<{
//  children: React.ReactNode;
//}>) {
//  return (
//    <html lang="en">
//      <body className={inter.className}>{children}</body>
//    </html>
//  );
//}
